name: DAST

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://10.3.70.25:8080/PortalManager/login'
          #rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
